### ISSUE TITLE
TiffOne Using Source code in solution

### ISSUE THREAD

**Issue by umitoguz** [Vogete/TiffOne#14]
Firstly thank for your big succes for this application.I want to integrate it to my solution  where alternatiff in my web page.Would u give advice for it.Thank You.

**Comment by Vogete** [comment]
I'm not sure I understand your needs. What is it you're trying to achieve?

**Comment by umitoguz** [comment]
I have solution in web app.In chrome it uses alternatiff.chrome version is 111.xx.Iunderstand halfly your source code.But i get some errors in running.Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'query')
    at loadChrome (background.js:10:17)
    at background.js:80:5 and ncaught (in promise) TypeError: Cannot read properties of undefined (reading 'local')
    at isEnabledResult (helper.js:8:28)
    at new Promise (<anonymous>)
    at helper.js:7:16
    at getEnabledState (helper.js:12:7)
    at setOnOffSwitchState (popup.js:10:27)
    at popup.js:35:1  and TiffOne is not defined.What is wrong?

**Comment by Vogete** [comment]
I'm still not sure I understand what you want to achieve. AlternaTIFF is an ActiveX plugin, which is no longer supported. How can you use that in Chrome 111?

Also, TiffOne is a browser extension (meant to somewhat replace AlternaTIFF). It should not be embedded into a web application. It's installed in a browser (right now only chromium based ones are supported), and then it can find embedded tiff images on a webpage, and make them visible.

If you want to develop a web application and display Tiff files (that's how I understand your issue), then TiffOne is not really your best solution. TiffOne is using [tiff.js](https://github.com/seikichi/tiff.js) to display tiff files, which can be embedded into a web application and used there.

_Please note, this project was originally made as a solution to a very specific problem that needed to be solved for my work. It should in theory be used to display any tiff file on a webpage, but the original scope was limited._

**Comment by umitoguz** [comment]
I have a web application that uses alternatiff. I need to take precautions since Internet explorer support will be reduced. I saw your tiffone extension. And I wanted to edit it and use it on google. The reason why I did this. Right now, when we enter the alternatiff test page(you should test that) through a google web browser with the new version, the tiffone extension works So I thought it would make sense to add this.Actually my only commands are instead of the existing alternatiff.By the way, congratulations, whatever the problem is, you have a good approach and solution.
